"""Type stubs for the `otspot` extension module.

abi3 extension modules carry no type information IDEs/mypy can introspect
at runtime, so this stub is the only source of type hints for `otspot`.
Keep it in sync with api_manifest.json (tests/test_api_manifest.py checks
the manifest against the built module, but not against this file).
"""

from __future__ import annotations

from typing import NoReturn, overload

__version__: str

class VarKind:
    Continuous: VarKind
    Integer: VarKind
    Binary: VarKind
    def __eq__(self, other: object) -> bool: ...
    def __int__(self) -> int: ...
    def __reduce__(self) -> tuple[object, ...]: ...

class SolutionProof:
    GlobalOptimal: SolutionProof
    LocalOptimal: SolutionProof
    FeasibleUnproven: SolutionProof
    Unknown: SolutionProof
    """Not a real otspot_core::problem::SolutionProof variant: the honest,
    payload-less fallback for a Rust variant this binding predates
    (SolutionProof is #[non_exhaustive])."""
    def __eq__(self, other: object) -> bool: ...
    def __int__(self) -> int: ...
    def __reduce__(self) -> tuple[object, ...]: ...

class SolveError:
    Infeasible: SolveError
    Unbounded: SolveError
    MaxIterations: SolveError
    Stalled: SolveError
    NumericalError: SolveError
    ResourceExhausted: SolveError
    Unknown: SolveError
    """See SolutionProof.Unknown's docstring; same rationale."""
    def __eq__(self, other: object) -> bool: ...
    def __int__(self) -> int: ...
    def __reduce__(self) -> tuple[object, ...]: ...

# SolveStatus/Tolerance variants are real Python subclasses of their parent
# at runtime (a PyO3 "complex enum"), not merely nested namespacing -- code
# written against this stub (including this package's own tests) relies on
# `isinstance(x, SolveStatus.Optimal)` narrowing `x`'s type, which mypy only
# supports when `SolveStatus.Optimal` is statically known to be a `type[T]`
# with `T` a subclass of `SolveStatus`. Top-level `_SolveStatus_*`/
# `_Tolerance_*` classes (not meant to be imported directly -- always go
# through `SolveStatus.Optimal`/`Tolerance.Medium` etc.) give mypy exactly
# that; a naive nested-class stub cannot express the subclass relationship
# without a self-reference to the not-yet-defined outer class.
class SolveStatus:
    """Hashable (usable as a `dict` key / `set` member), by variant + payload
    -- unlike `Tolerance` below, which is not (see its docstring)."""

    Optimal: type[_SolveStatus_Optimal]
    LocallyOptimal: type[_SolveStatus_LocallyOptimal]
    Infeasible: type[_SolveStatus_Infeasible]
    Unbounded: type[_SolveStatus_Unbounded]
    MaxIterations: type[_SolveStatus_MaxIterations]
    SuboptimalSolution: type[_SolveStatus_SuboptimalSolution]
    Stalled: type[_SolveStatus_Stalled]
    FeasiblePoint: type[_SolveStatus_FeasiblePoint]
    Timeout: type[_SolveStatus_Timeout]
    NumericalError: type[_SolveStatus_NumericalError]
    ResourceExhausted: type[_SolveStatus_ResourceExhausted]
    NonConvex: type[_SolveStatus_NonConvex]
    NonconvexLocal: type[_SolveStatus_NonconvexLocal]
    NonconvexGlobal: type[_SolveStatus_NonconvexGlobal]
    NotSupported: type[_SolveStatus_NotSupported]
    Unknown: type[_SolveStatus_Unknown]
    """Not a real otspot_core::problem::SolveStatus variant: the honest
    fallback carrying the original Display text, for a Rust variant this
    binding predates (SolveStatus is #[non_exhaustive])."""
    def __reduce__(self) -> tuple[object, ...]: ...

class _SolveStatus_Optimal(SolveStatus):
    def __init__(self) -> None: ...

class _SolveStatus_LocallyOptimal(SolveStatus):
    def __init__(self) -> None: ...

class _SolveStatus_Infeasible(SolveStatus):
    def __init__(self) -> None: ...

class _SolveStatus_Unbounded(SolveStatus):
    def __init__(self) -> None: ...

class _SolveStatus_MaxIterations(SolveStatus):
    def __init__(self) -> None: ...

class _SolveStatus_SuboptimalSolution(SolveStatus):
    def __init__(self) -> None: ...

class _SolveStatus_Stalled(SolveStatus):
    def __init__(self) -> None: ...

class _SolveStatus_FeasiblePoint(SolveStatus):
    def __init__(self) -> None: ...

class _SolveStatus_Timeout(SolveStatus):
    def __init__(self) -> None: ...

class _SolveStatus_NumericalError(SolveStatus):
    def __init__(self) -> None: ...

class _SolveStatus_ResourceExhausted(SolveStatus):
    def __init__(self) -> None: ...

class _SolveStatus_NonConvex(SolveStatus):
    def __init__(self, message: str) -> None: ...

class _SolveStatus_NonconvexLocal(SolveStatus):
    def __init__(self) -> None: ...

class _SolveStatus_NonconvexGlobal(SolveStatus):
    def __init__(self) -> None: ...

class _SolveStatus_NotSupported(SolveStatus):
    def __init__(self, message: str) -> None: ...

class _SolveStatus_Unknown(SolveStatus):
    def __init__(self, message: str) -> None: ...

class Tolerance:
    """NOT hashable (`hash(...)` raises `TypeError`), for every variant --
    not just `Custom(float)`: `Custom`'s `float` payload has no total-order-
    consistent hash (`NaN != NaN`), and PyO3 only supports hashing a whole
    `#[pyclass]` type, not per-variant, so `==` support alone (needed for
    `Tolerance.Medium() == Tolerance.Medium()`) already nulls out hashing for
    all of `Tolerance`, unlike `SolveStatus` above (no float payload,
    hashable)."""

    High: type[_Tolerance_High]
    Medium: type[_Tolerance_Medium]
    Fast: type[_Tolerance_Fast]
    Custom: type[_Tolerance_Custom]
    def __reduce__(self) -> tuple[object, ...]: ...

class _Tolerance_High(Tolerance):
    def __init__(self) -> None: ...

class _Tolerance_Medium(Tolerance):
    def __init__(self) -> None: ...

class _Tolerance_Fast(Tolerance):
    def __init__(self) -> None: ...

class _Tolerance_Custom(Tolerance):
    def __init__(self, eps: float) -> None: ...

class Variable:
    """Opaque handle to a decision variable.

    NOTE: `==`/`<=`/`>=` are NOT overloaded to build constraints (unlike
    some other modeling libraries) -- `x == 3.0` silently compares object
    identity (always False for distinct objects) instead of raising or
    building a constraint. Use `.leq()`/`.geq()`/`.eq_constraint()`, or the
    arithmetic operators (`+`, `-`, `*`, unary `-`) to build expressions.
    """

    # Solver-owned handle: only `Model.add_var`/`add_int_var`/`add_binary_var`
    # produce real instances (no `#[new]` on the Rust side, so `Variable()`
    # raises `TypeError` at runtime). `__init__` typed `NoReturn` (rather than
    # omitted, which would silently inherit `object.__init__`'s real `-> None`
    # and let mypy accept `Variable()` as well-typed) makes mypy flag any
    # direct-construction call site instead of type-checking it silently.
    # Same pattern on `Expression`/`QuadExpr`/`Constraint`/`ModelResult` below.
    # Trade-off: under `--warn-unreachable` (not enabled anywhere in this
    # repo today), mypy treats every line after a mistaken `Variable()` call
    # as unreachable and skips checking it, since `NoReturn` means "this call
    # never returns" -- so real type errors later in the same function could
    # go unnoticed if that flag is ever turned on.
    def __init__(self) -> NoReturn: ...
    def pow2(self) -> QuadExpr: ...
    def leq(self, rhs: Variable | Expression | float) -> Constraint: ...
    def geq(self, rhs: Variable | Expression | float) -> Constraint: ...
    def eq_constraint(self, rhs: Variable | Expression | float) -> Constraint: ...
    @overload
    def __add__(self, other: Variable | Expression | float) -> Expression: ...
    @overload
    def __add__(self, other: QuadExpr) -> QuadExpr: ...
    def __radd__(self, other: float) -> Expression: ...
    @overload
    def __sub__(self, other: Variable | Expression | float) -> Expression: ...
    @overload
    def __sub__(self, other: QuadExpr) -> QuadExpr: ...
    def __rsub__(self, other: float) -> Expression: ...
    @overload
    def __mul__(self, other: float) -> Expression: ...
    @overload
    def __mul__(self, other: Variable | Expression) -> QuadExpr: ...
    def __rmul__(self, other: float) -> Expression: ...
    def __neg__(self) -> Expression: ...

class Expression:
    """A linear expression. See `Variable`'s docstring for the `==`/`<=`/`>=`
    caveat -- it applies here too.

    `+`/`-` (via `__add__`/`__radd__`/`__sub__`/`__rsub__`) clone `self` on
    every call (Python's binary operators must not mutate either operand),
    so `total = total + term` in a loop is O(n) per step / O(n^2) overall.
    Prefer `total += term` (`__iadd__`): it mutates in place, no clone, so a
    long accumulation is O(n) overall instead. The one exception is `+=
    QuadExpr` (`expr += x.pow2()`), which raises `TypeError` -- `+=` cannot
    change `self`'s Python type from `Expression` to `QuadExpr` in place;
    use `expr = expr + x.pow2()` for that specific combination.
    """

    def __init__(self) -> NoReturn: ...
    def leq(self, rhs: Variable | Expression | float) -> Constraint: ...
    def geq(self, rhs: Variable | Expression | float) -> Constraint: ...
    def eq_constraint(self, rhs: Variable | Expression | float) -> Constraint: ...
    @overload
    def __add__(self, other: Variable | Expression | float) -> Expression: ...
    @overload
    def __add__(self, other: QuadExpr) -> QuadExpr: ...
    def __radd__(self, other: float) -> Expression: ...
    @overload
    def __iadd__(self, other: Variable | Expression | float) -> Expression: ...
    # NoReturn (not Expression): `expr += quad_expr` always raises TypeError
    # at runtime (Codex PR #31 review). Verified empirically that a direct
    # `expr.__iadd__(quad_expr)` call resolves to this overload (mypy reveals
    # `Never`), but mypy's `+=` augmented-assignment sugar does not consult a
    # NoReturn `__iadd__` overload the same way -- `expr += quad_expr` itself
    # is not flagged as an error either way. Dropping the overload entirely
    # (making mypy reject the call for lacking a match) was tried and rejected:
    # it triggers a separate "Signatures of __iadd__ and __add__ are
    # incompatible" error against `__add__`'s own QuadExpr overload above.
    @overload
    def __iadd__(self, other: QuadExpr) -> NoReturn: ...
    @overload
    def __sub__(self, other: Variable | Expression | float) -> Expression: ...
    @overload
    def __sub__(self, other: QuadExpr) -> QuadExpr: ...
    def __rsub__(self, other: float) -> Expression: ...
    @overload
    def __mul__(self, other: float) -> Expression: ...
    @overload
    def __mul__(self, other: Variable) -> QuadExpr: ...
    def __rmul__(self, other: float) -> Expression: ...
    def __neg__(self) -> Expression: ...

class QuadExpr:
    """A linear-or-quadratic objective expression (produced by `Variable.pow2()`
    or multiplying a `Variable`/`Expression` by another `Variable`).

    Prefer `total += term` over `total = total + term` in accumulation
    loops -- see `Expression`'s docstring; the same O(n) vs. O(n^2) tradeoff
    applies, and `QuadExpr.__iadd__` never raises (unlike `Expression`'s,
    since `QuadExpr` is already the "widest" DSL type).
    """

    def __init__(self) -> NoReturn: ...
    def is_linear(self) -> bool: ...
    def __add__(self, other: Variable | Expression | QuadExpr | float) -> QuadExpr: ...
    def __radd__(self, other: float) -> QuadExpr: ...
    def __iadd__(self, other: Variable | Expression | QuadExpr | float) -> QuadExpr: ...
    def __sub__(self, other: Variable | Expression | QuadExpr | float) -> QuadExpr: ...
    def __rsub__(self, other: float) -> QuadExpr: ...
    def __mul__(self, other: float) -> QuadExpr: ...
    def __rmul__(self, other: float) -> QuadExpr: ...
    def __neg__(self) -> QuadExpr: ...

class Constraint:
    """Opaque; construct via `Variable`/`Expression`'s `.leq()`/`.geq()`/
    `.eq_constraint()` and pass directly to `Model.add_constraint`."""

    def __init__(self) -> NoReturn: ...

class ModelResult:
    # PyO3-side: `#[getter]` only, no `#[setter]` (otspot-py/src/result.rs) --
    # `@property` (not a plain typed attribute) so mypy also rejects
    # `result.status = ...` as read-only, matching the runtime contract.
    # `__init__` typed `NoReturn`: only `Model.solve()` produces real
    # instances (no `#[new]` on the Rust side), see `Variable`'s docstring
    # above for why this is spelled out rather than omitted.
    def __init__(self) -> NoReturn: ...
    @property
    def status(self) -> SolveStatus: ...
    @property
    def proof(self) -> SolutionProof: ...
    @property
    def objective_value(self) -> float: ...
    @property
    def dual_solution(self) -> list[float] | None: ...
    @property
    def reduced_costs(self) -> list[float] | None: ...
    @property
    def slack(self) -> list[float] | None: ...
    @property
    def bound_duals(self) -> list[float]: ...

    def objective(self) -> float: ...
    def value(self, var: Variable) -> float: ...
    def has_global_optimality_proof(self) -> bool: ...
    def __getitem__(self, var: Variable) -> float: ...

class Model:
    """NOTE: not thread-safe for concurrent access to the *same* instance --
    PyO3 pyclasses use runtime borrow checking, so e.g. two threads calling
    `.solve()` on one shared `Model` raise `RuntimeError: Already borrowed`
    (or similar) rather than silently racing. Each thread needs its own
    `Model`. `.solve()` itself releases the GIL for its duration (see
    `Model.solve`'s docstring), so independent `Model`s *can* solve
    concurrently on separate threads.
    """

    def __init__(self, name: str) -> None: ...
    def add_var(self, name: str, lb: float, ub: float) -> Variable: ...
    def add_int_var(self, name: str, lb: float, ub: float) -> Variable: ...
    def add_binary_var(self, name: str) -> Variable: ...
    def var_name(self, var: Variable) -> str: ...
    def var_kind(self, var: Variable) -> VarKind: ...
    def add_constraint(self, constraint: Constraint) -> None: ...
    def minimize(self, objective: Variable | Expression | QuadExpr | float) -> None: ...
    def maximize(self, objective: Variable | Expression | QuadExpr | float) -> None: ...
    def set_timeout(self, secs: float) -> None: ...
    def set_tolerance(self, tolerance: Tolerance) -> None: ...
    def set_presolve(self, enabled: bool) -> None: ...
    def set_threads(self, n: int) -> None: ...
    def set_obj_offset(self, offset: float) -> None: ...
    def solve(self) -> ModelResult:
        """Runs with the GIL released (`Python::detach`): other Python
        threads make progress while this solve runs, and a long/unbounded
        (`timeout_secs` defaults to no limit) solve does not freeze
        `KeyboardInterrupt` delivery. Do not call concurrently on the same
        `Model` instance from multiple threads (see the class docstring)."""
        ...

class OtspotError(Exception): ...
class NoObjectiveError(OtspotError): ...
class InvalidInputError(OtspotError): ...

class SolveFailedError(OtspotError):
    error: SolveError

class TimeoutError(OtspotError): ...  # noqa: A001 -- intentionally shadows builtins.TimeoutError within this module's namespace only
class NonConvexError(OtspotError): ...
class InternalError(OtspotError): ...
