"""Type stubs for the `otspot` extension module.

abi3 extension modules carry no type information IDEs/mypy can introspect
at runtime, so this stub is the only source of type hints for `otspot`.
Keep it in sync with api_manifest.json (tests/test_api_manifest.py checks
the manifest against the built module, but not against this file).
"""

from __future__ import annotations

__version__: str

class VarKind:
    Continuous: VarKind
    Integer: VarKind
    Binary: VarKind
    def __eq__(self, other: object) -> bool: ...
    def __int__(self) -> int: ...

class SolutionProof:
    GlobalOptimal: SolutionProof
    LocalOptimal: SolutionProof
    FeasibleUnproven: SolutionProof
    def __eq__(self, other: object) -> bool: ...
    def __int__(self) -> int: ...

class SolveError:
    Infeasible: SolveError
    Unbounded: SolveError
    MaxIterations: SolveError
    Stalled: SolveError
    NumericalError: SolveError
    def __eq__(self, other: object) -> bool: ...
    def __int__(self) -> int: ...

class SolveStatus:
    class Optimal:
        def __init__(self) -> None: ...
    class LocallyOptimal:
        def __init__(self) -> None: ...
    class Infeasible:
        def __init__(self) -> None: ...
    class Unbounded:
        def __init__(self) -> None: ...
    class MaxIterations:
        def __init__(self) -> None: ...
    class SuboptimalSolution:
        def __init__(self) -> None: ...
    class Stalled:
        def __init__(self) -> None: ...
    class FeasiblePoint:
        def __init__(self) -> None: ...
    class Timeout:
        def __init__(self) -> None: ...
    class NumericalError:
        def __init__(self) -> None: ...
    class NonConvex:
        def __init__(self, message: str) -> None: ...
    class NonconvexLocal:
        def __init__(self) -> None: ...
    class NonconvexGlobal:
        def __init__(self) -> None: ...
    class NotSupported:
        def __init__(self, message: str) -> None: ...
    class Unknown:
        """Not a real otspot_core::problem::SolveStatus variant: the honest
        fallback when the Rust side returns a status this binding predates
        (SolveStatus is #[non_exhaustive])."""
        def __init__(self, message: str) -> None: ...

class Tolerance:
    class High:
        def __init__(self) -> None: ...
    class Medium:
        def __init__(self) -> None: ...
    class Fast:
        def __init__(self) -> None: ...
    class Custom:
        def __init__(self, eps: float) -> None: ...

class Variable:
    """Opaque handle to a decision variable.

    NOTE: `==`/`<=`/`>=` are NOT overloaded to build constraints (unlike
    some other modeling libraries) -- `x == 3.0` silently compares object
    identity (always False for distinct objects) instead of raising or
    building a constraint. Use `.leq()`/`.geq()`/`.eq_constraint()`, or the
    arithmetic operators (`+`, `-`, `*`, unary `-`) to build expressions.
    """

    def pow2(self) -> QuadExpr: ...
    def leq(self, rhs: Variable | Expression | float) -> Constraint: ...
    def geq(self, rhs: Variable | Expression | float) -> Constraint: ...
    def eq_constraint(self, rhs: Variable | Expression | float) -> Constraint: ...
    def __add__(self, other: Variable | Expression | QuadExpr | float) -> Expression | QuadExpr: ...
    def __radd__(self, other: float) -> Expression: ...
    def __sub__(self, other: Variable | Expression | QuadExpr | float) -> Expression | QuadExpr: ...
    def __rsub__(self, other: float) -> Expression: ...
    def __mul__(self, other: Variable | Expression | float) -> Expression | QuadExpr: ...
    def __rmul__(self, other: float) -> Expression: ...
    def __neg__(self) -> Expression: ...

class Expression:
    """A linear expression. See `Variable`'s docstring for the `==`/`<=`/`>=`
    caveat -- it applies here too."""

    def leq(self, rhs: Variable | Expression | float) -> Constraint: ...
    def geq(self, rhs: Variable | Expression | float) -> Constraint: ...
    def eq_constraint(self, rhs: Variable | Expression | float) -> Constraint: ...
    def __add__(self, other: Variable | Expression | QuadExpr | float) -> Expression | QuadExpr: ...
    def __radd__(self, other: float) -> Expression: ...
    def __sub__(self, other: Variable | Expression | QuadExpr | float) -> Expression | QuadExpr: ...
    def __rsub__(self, other: float) -> Expression: ...
    def __mul__(self, other: Variable | float) -> Expression | QuadExpr: ...
    def __rmul__(self, other: float) -> Expression: ...
    def __neg__(self) -> Expression: ...

class QuadExpr:
    """A linear-or-quadratic objective expression (produced by `Variable.pow2()`
    or multiplying a `Variable`/`Expression` by another `Variable`)."""

    def is_linear(self) -> bool: ...
    def __add__(self, other: Variable | Expression | QuadExpr | float) -> QuadExpr: ...
    def __radd__(self, other: float) -> QuadExpr: ...
    def __sub__(self, other: Variable | Expression | QuadExpr | float) -> QuadExpr: ...
    def __rsub__(self, other: float) -> QuadExpr: ...
    def __mul__(self, other: float) -> QuadExpr: ...
    def __rmul__(self, other: float) -> QuadExpr: ...
    def __neg__(self) -> QuadExpr: ...

class Constraint:
    """Opaque; construct via `Variable`/`Expression`'s `.leq()`/`.geq()`/
    `.eq_constraint()` and pass directly to `Model.add_constraint`."""

class ModelResult:
    status: SolveStatus
    proof: SolutionProof
    objective_value: float
    dual_solution: list[float] | None
    reduced_costs: list[float] | None
    slack: list[float] | None
    bound_duals: list[float]

    def objective(self) -> float: ...
    def value(self, var: Variable) -> float: ...
    def has_global_optimality_proof(self) -> bool: ...
    def __getitem__(self, var: Variable) -> float: ...

class Model:
    def __init__(self, name: str) -> None: ...
    def add_var(self, name: str, lb: float, ub: float) -> Variable: ...
    def add_int_var(self, name: str, lb: float, ub: float) -> Variable: ...
    def add_binary_var(self, name: str) -> Variable: ...
    def var_name(self, var: Variable) -> str: ...
    def var_kind(self, var: Variable) -> VarKind: ...
    def add_constraint(self, constraint: Constraint) -> None: ...
    def minimize(self, objective: Variable | Expression | QuadExpr | float) -> None: ...
    def maximize(self, objective: Variable | Expression | QuadExpr | float) -> None: ...
    def set_timeout(self, secs: float) -> None: ...
    def set_tolerance(self, tolerance: Tolerance) -> None: ...
    def set_presolve(self, enabled: bool) -> None: ...
    def set_threads(self, n: int) -> None: ...
    def set_obj_offset(self, offset: float) -> None: ...
    def solve(self) -> ModelResult: ...

class OtspotError(Exception): ...
class NoObjectiveError(OtspotError): ...
class InvalidInputError(OtspotError): ...

class SolveFailedError(OtspotError):
    error: SolveError

class TimeoutError(OtspotError): ...  # noqa: A001 -- intentionally shadows builtins.TimeoutError within this module's namespace only
class NonConvexError(OtspotError): ...
class InternalError(OtspotError): ...
