#!/usr/bin/env python3
"""Verify that every data/ path referenced by test code exists on disk.

Purpose (PR #25 issue #4): test-heavy.yml runs `--run-ignored all` as a
must-pass gate, and data-requiring tests panic on missing data by design
(no silent skip).  The set of data CI provides and the set of data tests
require are maintained in different places (workflow steps vs test sources)
and drift apart silently.  This script closes that gap structurally: run it
after CI data preparation and before the test run, and it fails fast with a
readable list instead of an opaque panic deep inside a long nextest run.

What it checks:
  1. Scans Rust sources for data-path references:
     tests/**/*.rs, */tests/**/*.rs, and crate src/**/*.rs unit tests
     (excluding src/bin/ and examples/, which are not executed by nextest).
     Three construction styles are resolved, because tests use all three:
       a. inline literal        "data/lp_problems/afiro.QPS"
       b. crate-relative literal Path::new(env!("CARGO_MANIFEST_DIR"))
                                     .join("../data/cblib_socp")
       c. constant-joined        const LP_SUBDIR = "lp_problems";
                                 fn data_dir(sub) { .join("../data").join(sub) }
                                 data_dir(LP_SUBDIR)
     Styles (b) and (c) are the ones the earlier pure-regex version missed;
     that blind spot is exactly the "silent drift" this gate exists to catch,
     so the extraction resolves crate-relative prefixes, per-file `&str`
     constants, and data-root helper functions (fns transitively grounded in
     a "data"/"../data" literal that then `.join(<arg>)`).
  2. A reference ending in a known data-file extension is a *file*
     requirement (the exact file must exist).  Any other reference is a
     *directory* requirement (the directory must exist and be non-empty).
  3. Missing requirements are failures (exit 1) UNLESS the dataset is in
     GRACEFUL_SKIP_DATASETS (warning only).  The default is intentionally
     "hard": that is the safe direction.  A dataset that has even one
     panic-on-missing consumer (e.g. data/maros_meszaros, asserted by
     cert_phase1_sentinel.rs) must stay hard so a real regression fails
     loudly — see the GRACEFUL_SKIP_DATASETS note for why CI-provided
     datasets are deliberately NOT listed even when some consumers skip.

Exit code: 0 = all hard requirements satisfied, 1 = at least one missing.

Usage:
    python3 scripts/check_test_data_requirements.py [--repo-root DIR]
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Datasets whose absence is tolerated (warning, not failure).
#
# Invariant — a dataset belongs here iff BOTH hold:
#   (1) it is NOT provided by CI (not in download_all_bench_data.sh --ci-subset
#       nor generated by a test-heavy.yml step), and
#   (2) EVERY test that touches it skips gracefully on absence
#       (`if !path.exists() { return; }` / candidate-path fallback), i.e. no
#       consumer asserts existence or unwraps a parse of a missing file.
#
# Deliberately excluded even though some of their consumers skip gracefully:
#   - maros_meszaros, lp_problems, lp_problems_infeas, qplib, miplib_small:
#     CI-provided AND have panic-on-missing consumers. Listing them would
#     downgrade a genuine "CI stopped providing this" regression to a warning.
# Enumeration of graceful-skip tests was cross-checked against the CI subset;
# the only not-provided, all-skip datasets are the three below.
GRACEFUL_SKIP_DATASETS: dict[str, str] = {
    # tests/cbf_feasibility.rs + otspot-io/tests/cbf_cblib_integration.rs:
    # both `if !path/dir.exists() { eprintln!(skip); return; }`.
    "cblib_socp": "cbf_feasibility / cbf_cblib_integration skip when absent",
    # otspot-io/src/qplib/mod.rs unit tests: `if !path.exists() { return; }`
    "qplib_unsupported": "otspot-io qplib unit tests skip when absent",
    # diag_greenbea_dfeas.rs / diag_etamacro_dfeas.rs list the canary dir as
    # the first path candidate and fall back to data/lp_problems (which is a
    # hard requirement checked separately via its own references).
    "lp_problems_canary": "candidate path with fallback to data/lp_problems",
}

# Extensions that identify a reference as a concrete data-file requirement.
DATA_FILE_EXTS = {
    ".qps", ".qplib", ".mps", ".cbf", ".csv", ".npz", ".mat", ".lp", ".sif",
}

# A `data/<subpath>` segment inside a string literal, tolerating any number of
# leading `../` (crate-relative refs like "../data/cblib_socp").  The
# lookbehind rejects a preceding word char so "metadata/x" does NOT match, and
# rejects a preceding `/` so absolute "/data/..." (CSV-routing fixtures in
# otspot-dev/src/bench_utils.rs) is not treated as a requirement.  The subpath
# stops at the first non-path char, so a `format!` placeholder truncates to the
# containing directory: "data/lp_problems/{}.QPS" → data/lp_problems.
DATA_SEG_RE = re.compile(
    r'(?<![A-Za-z0-9_/])(?:\.\./)*data/([A-Za-z0-9_][A-Za-z0-9_./-]*)')

# A bare data-root string literal ("data" or "../data"): the base a helper or
# join-chain appends a subdir onto.
DATA_ROOT_LIT_RE = re.compile(r'"(?:\.\./)*data"')

# `const NAME: &str = "value";` (per-file string constants used as subdirs).
CONST_RE = re.compile(r'const\s+(\w+)\s*:\s*&(?:\'\w+\s+)?str\s*=\s*"([^"]*)"')

# String literal (single-line) for scanning literal values.
STRING_LIT_RE = re.compile(r'"([^"\n]*)"')


def rust_sources(root: Path) -> list[Path]:
    """Rust files whose tests nextest executes: integration tests and
    in-crate unit tests.  Excludes bins/examples (not run as tests) and
    build artifacts / nested worktrees."""
    results: list[Path] = []
    for path in root.rglob("*.rs"):
        rel_parts = path.relative_to(root).parts
        if any(p in ("target", ".claude", ".codex-worktrees", "examples") for p in rel_parts):
            continue
        if "bin" in rel_parts and "src" in rel_parts:
            continue
        if "tests" in rel_parts or "src" in rel_parts:
            results.append(path)
    return results


def _fn_bodies(text: str) -> list[tuple[str, list[str], str]]:
    """Return (name, param_names, body) for each `fn name(...) { ... }`.

    Bodies are extracted by brace matching from the first `{` after the
    parameter list.  Good enough for the flat test helpers in this repo.
    """
    out: list[tuple[str, list[str], str]] = []
    for m in re.finditer(r'\bfn\s+(\w+)\s*\(', text):
        name = m.group(1)
        i = m.end() - 1  # at the '('
        depth = 0
        while i < len(text):
            c = text[i]
            if c == '(':
                depth += 1
            elif c == ')':
                depth -= 1
                if depth == 0:
                    break
            i += 1
        params_str = text[m.end():i]
        params = [p.strip().split(':')[0].strip().lstrip('&').strip()
                  for p in params_str.split(',') if ':' in p]
        brace = text.find('{', i)
        if brace == -1:
            continue
        depth = 0
        j = brace
        while j < len(text):
            c = text[j]
            if c == '{':
                depth += 1
            elif c == '}':
                depth -= 1
                if depth == 0:
                    break
            j += 1
        out.append((name, params, text[brace:j + 1]))
    return out


def _resolve_arg(arg: str, consts: dict[str, str]) -> str | None:
    """Resolve a call/join argument to a literal subpath, or None if dynamic."""
    arg = arg.strip()
    lit = re.fullmatch(r'"([^"]*)"', arg)
    if lit:
        return lit.group(1)
    if re.fullmatch(r'\w+', arg) and arg in consts:
        return consts[arg]
    return None


def _norm(subpath: str) -> str | None:
    """Normalise a resolved subpath to a `data/<...>` requirement, or None."""
    subpath = subpath.strip().strip('/')
    if not subpath:
        return None
    return f"data/{subpath}"


def _data_helpers(bodies: list[tuple[str, list[str], str]]) -> set[str]:
    """Names of fns transitively grounded in a data-root literal that then
    append a parameter — i.e. `helper(sub)` yields `data/<sub>`."""
    grounded: set[str] = set()
    # Seed: body contains a bare data-root literal ("data" / "../data").
    for name, _params, body in bodies:
        if DATA_ROOT_LIT_RE.search(body):
            grounded.add(name)
    # Propagate: a fn that calls a grounded helper is itself grounded.
    changed = True
    while changed:
        changed = False
        for name, _params, body in bodies:
            if name in grounded:
                continue
            if any(re.search(rf'\b{re.escape(g)}\s*\(', body) for g in grounded):
                grounded.add(name)
                changed = True
    # Keep only the parametric ones: body does `.join(<param>)`.
    parametric: set[str] = set()
    for name, params, body in bodies:
        if name not in grounded:
            continue
        if any(re.search(rf'\.join\(\s*{re.escape(p)}\b', body) for p in params if p):
            parametric.add(name)
    return parametric


def _file_requirements(text: str) -> set[str]:
    """All `data/<...>` requirements resolvable within a single source file."""
    reqs: set[str] = set()
    consts = {m.group(1): m.group(2) for m in CONST_RE.finditer(text)}

    # (a)/(b) literal segments, including crate-relative "../data/...".
    for val_m in STRING_LIT_RE.finditer(text):
        seg = DATA_SEG_RE.search(val_m.group(0))
        if seg:
            r = _norm(seg.group(1))
            if r:
                reqs.add(r)

    # (c) data-root helper call sites: helper(ARG) and helper().join(ARG).
    helpers = _data_helpers(_fn_bodies(text))
    for h in helpers:
        for call in re.finditer(rf'\b{re.escape(h)}\s*\(\s*([^())]*?)\s*\)', text):
            arg = call.group(1)
            if arg:
                sub = _resolve_arg(arg, consts)
                if sub is not None:
                    r = _norm(sub)
                    if r:
                        reqs.add(r)
        for call in re.finditer(rf'\b{re.escape(h)}\s*\(\s*\)\s*\.join\(\s*([^())]*?)\s*\)', text):
            sub = _resolve_arg(call.group(1), consts)
            if sub is not None:
                r = _norm(sub)
                if r:
                    reqs.add(r)

    # (c') inline data-root join chain without a named helper:
    #      Path::new(..).join("../data").join(SUB)
    for m in re.finditer(r'"(?:\.\./)*data"\s*\)?\s*\.join\(\s*([^())]*?)\s*\)', text):
        sub = _resolve_arg(m.group(1), consts)
        if sub is not None:
            r = _norm(sub)
            if r:
                reqs.add(r)
    return reqs


def collect_requirements(root: Path) -> dict[str, set[str]]:
    """Map of data-path requirement → set of referencing source files."""
    reqs: dict[str, set[str]] = {}
    for src in rust_sources(root):
        try:
            text = src.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for ref in _file_requirements(text):
            if ref.count("/") < 1 or ref == "data":
                continue
            reqs.setdefault(ref, set()).add(str(src.relative_to(root)))
    return reqs


def classify(ref: str) -> str:
    """'file' if the last segment carries a known data extension, else 'dir'."""
    suffix = Path(ref).suffix.lower()
    return "file" if suffix in DATA_FILE_EXTS else "dir"


def check(root: Path) -> int:
    reqs = collect_requirements(root)
    missing_hard: list[tuple[str, str, list[str]]] = []
    missing_soft: list[tuple[str, str, list[str]]] = []
    ok_count = 0

    for ref in sorted(reqs):
        kind = classify(ref)
        path = root / ref
        if kind == "file":
            present = path.is_file()
        else:
            present = path.is_dir() and any(path.iterdir())
        if present:
            ok_count += 1
            continue
        dataset = ref.split("/")[1]
        entry = (ref, kind, sorted(reqs[ref]))
        if dataset in GRACEFUL_SKIP_DATASETS:
            missing_soft.append(entry)
        else:
            missing_hard.append(entry)

    print(f"[check_test_data_requirements] {len(reqs)} referenced data paths: "
          f"{ok_count} ok, {len(missing_soft)} skip-tolerant missing, "
          f"{len(missing_hard)} REQUIRED missing")

    for ref, kind, sources in missing_soft:
        dataset = ref.split("/")[1]
        reason = GRACEFUL_SKIP_DATASETS[dataset]
        print(f"\n[warn] missing {kind}: {ref}  (graceful skip: {reason})")
        for s in sources:
            print(f"       referenced by {s}")

    sys.stdout.flush()
    for ref, kind, sources in missing_hard:
        print(f"\n[FAIL] missing {kind}: {ref}", file=sys.stderr)
        for s in sources:
            print(f"       referenced by {s}", file=sys.stderr)

    if missing_hard:
        print(
            "\n[check_test_data_requirements] FAILED — tests referencing the "
            "paths above will panic ('data missing'). Provide the data in the "
            "CI data-preparation steps (see .github/workflows/test-heavy.yml) "
            "or, if the referencing test skips gracefully, add its dataset to "
            "GRACEFUL_SKIP_DATASETS with a reason.",
            file=sys.stderr,
        )
        return 1
    print("[check_test_data_requirements] all required data present")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--repo-root", default=None,
                        help="Repo root directory (default: parent of scripts/)")
    args = parser.parse_args()
    root = (Path(args.repo_root).resolve() if args.repo_root
            else Path(__file__).resolve().parent.parent)
    return check(root)


if __name__ == "__main__":
    sys.exit(main())
