#!/bin/bash
# Extended QCQP instances downloader (additional 35 instances).
#
# Scope: Continuous vars (V=C), Quadratic objective (O in Q/D),
# Quadratic constraints allowed (C in L/B/N/Q).
# Excludes already-tracked instances and binary/integer/mixed vars.
#
# Source: https://qplib.zib.de/qplib/QPLIB_XXXX.qplib
# ID list: data/qplib_filtered/extended_ids.txt (generated by qplib_filter.sh)
#
# Usage:
#   bash scripts/qplib_extended_download.sh [OUT_DIR]
# OUT_DIR defaults to data/qplib_extended

set -euo pipefail

OUT_DIR="${1:-data/qplib_extended}"
ID_FILE="${ID_FILE:-data/qplib_filtered/extended_ids.txt}"

mkdir -p "$OUT_DIR"

if [[ ! -f "$ID_FILE" ]]; then
  echo "[error] ID list not found: $ID_FILE" >&2
  echo "[info] run: bash scripts/qplib_filter.sh" >&2
  exit 1
fi

total=$(wc -l < "$ID_FILE")
ok=0
skip=0
fail=0
fail_ids=""

echo "[info] downloading $total instances from $ID_FILE"

while IFS= read -r id || [[ -n "$id" ]]; do
  id=$(echo "$id" | xargs)  # trim whitespace
  [[ -z "$id" ]] && continue

  out="$OUT_DIR/QPLIB_${id}.qplib"
  if [[ -s "$out" ]]; then
    skip=$((skip + 1))
    continue
  fi
  tmp=$(mktemp)
  if curl -fsSL "https://qplib.zib.de/qplib/QPLIB_${id}.qplib" -o "$tmp"; then
    mv "$tmp" "$out"
    ok=$((ok + 1))
    echo "[ok]   QPLIB_${id}"
  else
    rm -f "$tmp"
    fail=$((fail + 1))
    fail_ids="$fail_ids $id"
    echo "[fail] QPLIB_${id}"
  fi
done < "$ID_FILE"

echo ""
echo "[summary] qplib_extended: ok=$ok skip=$skip fail=$fail total=$total -> $OUT_DIR"
if (( fail > 0 )); then
  echo "[fail-ids]$fail_ids"
  exit 1
fi
